FROM tomcat:8.5.31-jre8
RUN rm -rvf /usr/local/tomcat/webapps/ROOT
ADD  /target/coins-0.0.1-SNAPSHOT.jar /usr/local/tomcat/webapps/ROOT.jar
CMD ["catalina.sh", "run"]
EXPOSE 8080
 or:
FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar /app.jar"]
EXPOSE 8080
